### PR TITLE
Settings Update

### PR DESCRIPTION
**Pull request by JohnnnnyKlayy**
- Added a settings menu
  - Share logs automatically
  - Optionally include Discord so we can contact you
  - Preview command before it runs
    - Copy command to clipboard and run
    - Copy only
    - Run only

### CODE REVIEW

**Comment by JohnnnnyKlayy** [comment]
wait. I wanted to merge dev into master not this way lol

**Comment by JohnnnnyKlayy** [comment]
Never mind? think I'm blind idk

**Comment by F0lkl0re** [comment]
I think its good. Its dev to master

**Comment by JohnnnnyKlayy** [comment]
ty ily <3

**Pull request merged**
